package com.mariano.swing.gui;

/**
 *
 * @author Maria
 */
public class NextOption extends javax.swing.JFrame {

    /**
     * Creates new form NextOption
     */
    public NextOption() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Return = new javax.swing.JButton();
        PrincipalTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Return.setBackground(new java.awt.Color(51, 255, 0));
        Return.setForeground(new java.awt.Color(0, 0, 0));
        Return.setText("Return");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });
        jPanel2.add(Return, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        PrincipalTitle.setBackground(new java.awt.Color(0, 0, 0));
        PrincipalTitle.setFont(new java.awt.Font("Britannic Bold", 0, 12)); // NOI18N
        PrincipalTitle.setForeground(new java.awt.Color(0, 0, 0));
        PrincipalTitle.setIcon(new javax.swing.ImageIcon("C:\\Users\\Maria\\OneDrive\\Documentos\\NetBeansProjects\\Swing\\src\\main\\resource\\images\\communityIcon_ja7r667y4np11.png")); // NOI18N
        jPanel2.add(PrincipalTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 260, 250));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
        new Principal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReturnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PrincipalTitle;
    private javax.swing.JButton Return;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
