package com.mariano.ipc1.gui;

import com.mariano.ipc1.threads.TimeThread;
import javax.swing.JFrame;

/**
 *
 * @author Mariano Camposeco {@literal (mariano1941@outlook.es)}
 */
public class Principal extends JFrame {

    private TimeThread timeThread;
    private TimeThread timeThread2;
    private boolean isPaused = false;
    private boolean isPaused2 = false;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        timeBar = new javax.swing.JProgressBar();
        resetTimeButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        startTime = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        pauseAndResumeButton = new javax.swing.JButton();
        stopButton = new javax.swing.JButton();
        startTime2 = new javax.swing.JButton();
        resetTimeButton2 = new javax.swing.JButton();
        pauseAndResumeButton2 = new javax.swing.JButton();
        stopButton2 = new javax.swing.JButton();
        timeBar2 = new javax.swing.JProgressBar();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Threads");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        timeBar.setBackground(new java.awt.Color(255, 255, 255));
        timeBar.setForeground(new java.awt.Color(0, 255, 0));
        jPanel1.add(timeBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 420, 29));

        resetTimeButton.setBackground(new java.awt.Color(255, 255, 51));
        resetTimeButton.setForeground(new java.awt.Color(0, 0, 0));
        resetTimeButton.setText("Reset Time");
        resetTimeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetTimeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(resetTimeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 100, 40));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Time 1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, -1, -1));

        startTime.setBackground(new java.awt.Color(0, 255, 0));
        startTime.setForeground(new java.awt.Color(0, 0, 0));
        startTime.setText("Start Time");
        startTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTimeActionPerformed(evt);
            }
        });
        jPanel1.add(startTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Threads");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 0, -1, -1));

        pauseAndResumeButton.setBackground(new java.awt.Color(255, 102, 0));
        pauseAndResumeButton.setForeground(new java.awt.Color(0, 0, 0));
        pauseAndResumeButton.setText("P / R");
        pauseAndResumeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseAndResumeButtonActionPerformed(evt);
            }
        });
        jPanel1.add(pauseAndResumeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 90, 40));

        stopButton.setBackground(new java.awt.Color(255, 0, 0));
        stopButton.setForeground(new java.awt.Color(0, 0, 0));
        stopButton.setText("Stop");
        stopButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButtonActionPerformed(evt);
            }
        });
        jPanel1.add(stopButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 60, 40));

        startTime2.setBackground(new java.awt.Color(0, 255, 0));
        startTime2.setForeground(new java.awt.Color(0, 0, 0));
        startTime2.setText("Start Time");
        startTime2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startTime2ActionPerformed(evt);
            }
        });
        jPanel1.add(startTime2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 40));

        resetTimeButton2.setBackground(new java.awt.Color(255, 255, 51));
        resetTimeButton2.setForeground(new java.awt.Color(0, 0, 0));
        resetTimeButton2.setText("Reset Time");
        resetTimeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetTimeButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(resetTimeButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 100, 40));

        pauseAndResumeButton2.setBackground(new java.awt.Color(255, 102, 0));
        pauseAndResumeButton2.setForeground(new java.awt.Color(0, 0, 0));
        pauseAndResumeButton2.setText("P / R");
        pauseAndResumeButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pauseAndResumeButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(pauseAndResumeButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 90, 40));

        stopButton2.setBackground(new java.awt.Color(255, 0, 0));
        stopButton2.setForeground(new java.awt.Color(0, 0, 0));
        stopButton2.setText("Stop");
        stopButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stopButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(stopButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 60, 40));

        timeBar2.setBackground(new java.awt.Color(255, 255, 255));
        timeBar2.setForeground(new java.awt.Color(0, 255, 0));
        jPanel1.add(timeBar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 420, 29));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Time 2");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resetTimeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetTimeButtonActionPerformed
        if (timeThread != null && timeThread.isAlive()) {
            timeBar.setValue(100);
        }
    }//GEN-LAST:event_resetTimeButtonActionPerformed

    private void startTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTimeActionPerformed
        if (timeThread == null || !timeThread.isAlive()) {
            timeThread = new TimeThread(timeBar);
            timeThread.start();
        }
    }//GEN-LAST:event_startTimeActionPerformed

    private void pauseAndResumeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseAndResumeButtonActionPerformed
        if (timeThread != null && timeThread.isAlive()) {
            if (isPaused) {
                timeThread.resumeThread();
                pauseAndResumeButton.setText("Pause");
                isPaused = false;
            } else {
                timeThread.pauseThread();
                pauseAndResumeButton.setText("Resume");
                isPaused = true;
            }
        }
    }//GEN-LAST:event_pauseAndResumeButtonActionPerformed

    private void stopButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButtonActionPerformed
        if (timeThread != null && timeThread.isAlive()) {
            timeThread.stopThread();
        }

        isPaused = false;
        pauseAndResumeButton.setText("P / R");
        timeBar.setValue(0);
    }//GEN-LAST:event_stopButtonActionPerformed

    private void startTime2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startTime2ActionPerformed
        if (timeThread2 == null || !timeThread2.isAlive()) {
            timeThread2 = new TimeThread(timeBar2);
            timeThread2.start();
        }
    }//GEN-LAST:event_startTime2ActionPerformed

    private void resetTimeButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetTimeButton2ActionPerformed
        if (timeThread2 != null && timeThread2.isAlive()) {
            timeBar2.setValue(100);
        }
    }//GEN-LAST:event_resetTimeButton2ActionPerformed

    private void pauseAndResumeButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pauseAndResumeButton2ActionPerformed
        if (timeThread2 != null && timeThread2.isAlive()) {
            if (isPaused2) {
                timeThread2.resumeThread();
                pauseAndResumeButton2.setText("Pause");
                isPaused2 = false;
            } else {
                timeThread2.pauseThread();
                pauseAndResumeButton2.setText("Resume");
                isPaused2 = true;
            }
        }
    }//GEN-LAST:event_pauseAndResumeButton2ActionPerformed

    private void stopButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stopButton2ActionPerformed
        if (timeThread2 != null && timeThread2.isAlive()) {
            timeThread2.stopThread();
        }

        pauseAndResumeButton2.setText("P / R");
        timeBar2.setValue(0);
    }//GEN-LAST:event_stopButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton pauseAndResumeButton;
    private javax.swing.JButton pauseAndResumeButton2;
    private javax.swing.JButton resetTimeButton;
    private javax.swing.JButton resetTimeButton2;
    private javax.swing.JButton startTime;
    private javax.swing.JButton startTime2;
    private javax.swing.JButton stopButton;
    private javax.swing.JButton stopButton2;
    private javax.swing.JProgressBar timeBar;
    private javax.swing.JProgressBar timeBar2;
    // End of variables declaration//GEN-END:variables
}
